Tell travis scripts to exit none 0 when called command fails. Re: 139

diff --git a/travis/before_install b/travis/before_install
--- a/travis/before_install
+++ b/travis/before_install
@@ -1,8 +1,15 @@
 #!/bin/bash
 
+#Tell bash to exit none 0 on failing command
+set -e
+
 . "$(dirname $0)/util.sh"
 
 if [ $is_osx ]; then
+    #perlbrew install perl-"$TRAVIS_PERL_VERSION"
+    perl -v
+    perlbrew use perl-"$TRAVIS_PERL_VERSION"
+    perl -v
     brew install cpanminus
 fi
 
